/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Chu Quynh Beo
 */
public class JFrame_CSVC extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyCoSoVatChat
     */
    public JFrame_CSVC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ibl_MaCSVC = new javax.swing.JLabel();
        Ibl_LoaiCSVC = new javax.swing.JLabel();
        Ibl_GiaCSVC = new javax.swing.JLabel();
        txt_MaCSVC = new javax.swing.JTextField();
        txt_LoaiCSVC = new javax.swing.JTextField();
        txt_GiaCSVC = new javax.swing.JTextField();
        btn_ThemCSVC = new javax.swing.JButton();
        btn_SuaCSVC = new javax.swing.JButton();
        btn_XoaCSVC = new javax.swing.JButton();
        cbx_Loc = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ibl_MaCSVC.setText("Mã CSVC");

        Ibl_LoaiCSVC.setText("Loại CSVC");

        Ibl_GiaCSVC.setText("Giá CSVC");

        txt_MaCSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaCSVCActionPerformed(evt);
            }
        });

        txt_GiaCSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaCSVCActionPerformed(evt);
            }
        });

        btn_ThemCSVC.setText("Thêm");

        btn_SuaCSVC.setText("Sửa");
        btn_SuaCSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaCSVCActionPerformed(evt);
            }
        });

        btn_XoaCSVC.setText("Xóa");
        btn_XoaCSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaCSVCActionPerformed(evt);
            }
        });

        cbx_Loc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lọc", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Danh Sách CSVC");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã CSVC", "Loại CSVC", "Giá CSVC"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Ibl_MaCSVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ibl_LoaiCSVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Ibl_GiaCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MaCSVC)
                                    .addComponent(txt_LoaiCSVC)
                                    .addComponent(txt_GiaCSVC)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btn_ThemCSVC)
                                .addGap(79, 79, 79)
                                .addComponent(btn_SuaCSVC)
                                .addGap(87, 87, 87)
                                .addComponent(btn_XoaCSVC)
                                .addGap(85, 85, 85)
                                .addComponent(cbx_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator2)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ibl_MaCSVC)
                    .addComponent(txt_MaCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ibl_LoaiCSVC)
                    .addComponent(txt_LoaiCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ibl_GiaCSVC)
                    .addComponent(txt_GiaCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemCSVC)
                    .addComponent(btn_SuaCSVC)
                    .addComponent(btn_XoaCSVC)
                    .addComponent(cbx_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaCSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaCSVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaCSVCActionPerformed

    private void txt_GiaCSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaCSVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaCSVCActionPerformed

    private void btn_XoaCSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaCSVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaCSVCActionPerformed

    private void btn_SuaCSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaCSVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SuaCSVCActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ibl_GiaCSVC;
    private javax.swing.JLabel Ibl_LoaiCSVC;
    private javax.swing.JLabel Ibl_MaCSVC;
    private javax.swing.JButton btn_SuaCSVC;
    private javax.swing.JButton btn_ThemCSVC;
    private javax.swing.JButton btn_XoaCSVC;
    private javax.swing.JComboBox<String> cbx_Loc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_GiaCSVC;
    private javax.swing.JTextField txt_LoaiCSVC;
    private javax.swing.JTextField txt_MaCSVC;
    // End of variables declaration//GEN-END:variables
}
