/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;

/**
 *
 * @author huylequang
 */
public class JFrame_Main extends javax.swing.JFrame {
    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        setTitle("66IT2 - Nhóm 1 - Hệ Thống Quản Lý Phòng Họp");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_PhongHop = new javax.swing.JMenu();
        jMenu_KhachHang = new javax.swing.JMenu();
        jMenu_CoSoVatChat = new javax.swing.JMenu();
        jMenu_PhienThue = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("ĐỒ ÁN OOP");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("ĐỀ TÀI: HỆ THỐNG QUẢN LÝ PHÒNG HỌP");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logohuce_1.png"))); // NOI18N

        jMenu_PhongHop.setText("Phòng Họp");
        jMenu_PhongHop.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_PhongHopMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_PhongHop);

        jMenu_KhachHang.setText("Khách Hàng");
        jMenu_KhachHang.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_KhachHangMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_KhachHang);

        jMenu_CoSoVatChat.setText("Cơ Sở Vật Chất");
        jMenu_CoSoVatChat.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_CoSoVatChatMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_CoSoVatChat);

        jMenu_PhienThue.setText("Phiên Thuê");
        jMenu_PhienThue.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_PhienThueMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_PhienThue);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Bắt sự kiện khi bấm nút ở trên các Menu
    private void jMenu_PhongHopMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_PhongHopMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_PhongHopMenuSelected

    private void jMenu_KhachHangMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_KhachHangMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_KhachHangMenuSelected

    private void jMenu_CoSoVatChatMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_CoSoVatChatMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_CoSoVatChatMenuSelected

    private void jMenu_PhienThueMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_PhienThueMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_PhienThueMenuSelected

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getjMenu_CoSoVatChat() {
        return jMenu_CoSoVatChat;
    }

    public void setjMenu_CoSoVatChat(JMenu jMenu_CoSoVatChat) {
        this.jMenu_CoSoVatChat = jMenu_CoSoVatChat;
    }

    public JMenu getjMenu_KhachHang() {
        return jMenu_KhachHang;
    }

    public void setjMenu_KhachHang(JMenu jMenu_KhachHang) {
        this.jMenu_KhachHang = jMenu_KhachHang;
    }

    public JMenu getjMenu_PhienThue() {
        return jMenu_PhienThue;
    }

    public void setjMenu_PhienThue(JMenu jMenu_PhienThue) {
        this.jMenu_PhienThue = jMenu_PhienThue;
    }

    public JMenu getjMenu_PhongHop() {
        return jMenu_PhongHop;
    }

    public void setjMenu_PhongHop(JMenu jMenu_PhongHop) {
        this.jMenu_PhongHop = jMenu_PhongHop;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_CoSoVatChat;
    private javax.swing.JMenu jMenu_KhachHang;
    private javax.swing.JMenu jMenu_PhienThue;
    private javax.swing.JMenu jMenu_PhongHop;
    // End of variables declaration//GEN-END:variables
}
