/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author huylequang
 */
public class JFrame_Main extends javax.swing.JFrame {
    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        setTitle("66IT2 - Nhóm 1 - Hệ Thống Quản Lý Phòng Họp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_PhongHop = new javax.swing.JMenu();
        jMenu_KhachHang = new javax.swing.JMenu();
        jMenu_CoSoVatChat = new javax.swing.JMenu();
        jMenu_PhienThue = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("ĐỒ ÁN OOP");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("ĐỀ TÀI: HỆ THỐNG QUẢN LÝ PHÒNG HỌP");

        jMenu_PhongHop.setText("Phòng Họp");
        jMenu_PhongHop.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_PhongHopMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_PhongHop);

        jMenu_KhachHang.setText("Khách Hàng");
        jMenu_KhachHang.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_KhachHangMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_KhachHang);

        jMenu_CoSoVatChat.setText("Cơ Sở Vật Chất");
        jMenu_CoSoVatChat.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_CoSoVatChatMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_CoSoVatChat);

        jMenu_PhienThue.setText("Phiên Thuê");
        jMenu_PhienThue.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_PhienThueMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu_PhienThue);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Bắt sự kiện khi bấm nút ở trên các Menu
    private void jMenu_PhongHopMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_PhongHopMenuSelected
        // TODO add your handling code here:
        JFrame_PhongHop frm_phonghop = new JFrame_PhongHop();
        frm_phonghop.setVisible(true);
    }//GEN-LAST:event_jMenu_PhongHopMenuSelected

    private void jMenu_KhachHangMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_KhachHangMenuSelected
        // TODO add your handling code here:
        JFrame_KhachHang frm_khachhang = new JFrame_KhachHang();
        frm_khachhang.setVisible(true);
    }//GEN-LAST:event_jMenu_KhachHangMenuSelected

    private void jMenu_CoSoVatChatMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_CoSoVatChatMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_CoSoVatChatMenuSelected

    private void jMenu_PhienThueMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_PhienThueMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_PhienThueMenuSelected

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_CoSoVatChat;
    private javax.swing.JMenu jMenu_KhachHang;
    private javax.swing.JMenu jMenu_PhienThue;
    private javax.swing.JMenu jMenu_PhongHop;
    // End of variables declaration//GEN-END:variables
}
