/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author huylequang
 */
public class MainForm extends javax.swing.JFrame {
    private static String maNV;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setTitle("66IT2 - Nhóm 1 - Hệ Thống Quản Lý Phòng Họp");
        this.getLbl_Username().setText(maNV);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbed_FrmMain = new javax.swing.JTabbedPane();
        jPanel_KhachHang = new javax.swing.JPanel();
        lbl_MaKH = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        lbl_TenKhachHang = new javax.swing.JLabel();
        txt_TenKhachHang = new javax.swing.JTextField();
        lbl_SDTKhachHang = new javax.swing.JLabel();
        txt_SDTKhachHang = new javax.swing.JTextField();
        btn_ThemKhachHang = new javax.swing.JButton();
        btn_SuaKhachHang = new javax.swing.JButton();
        btn_XoaKhachHang = new javax.swing.JButton();
        btn_TimKhachHang = new javax.swing.JButton();
        jScrollPaneKhachHang = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        jPanel_PhongHop = new javax.swing.JPanel();
        lbl_MaPhong = new javax.swing.JLabel();
        txt_MaPhong = new javax.swing.JTextField();
        lbl_LoaiPhong = new javax.swing.JLabel();
        txt_LoaiPhong = new javax.swing.JTextField();
        lbl_GiaTien = new javax.swing.JLabel();
        txt_GiaTien = new javax.swing.JTextField();
        btn_ThemPhong = new javax.swing.JButton();
        btn_SuaPhong = new javax.swing.JButton();
        btn_XoaPhong = new javax.swing.JButton();
        btn_TimPhong = new javax.swing.JButton();
        jScrollPane_Phong = new javax.swing.JScrollPane();
        tbl_PhongHop = new javax.swing.JTable();
        jPanel_CoSoVatChat = new javax.swing.JPanel();
        lbl_MaCSVC = new javax.swing.JLabel();
        txt_MaCSVC = new javax.swing.JTextField();
        lbl_LoaiCSVC = new javax.swing.JLabel();
        txt_LoaiCSVC = new javax.swing.JTextField();
        lbl_GiaCSVC = new javax.swing.JLabel();
        txt_GiaCSVC = new javax.swing.JTextField();
        btn_ThemCSVC = new javax.swing.JButton();
        btn_SuaCSVC = new javax.swing.JButton();
        btn_XoaCSVC = new javax.swing.JButton();
        btn_TimCSVC = new javax.swing.JButton();
        jScrollPane_CSVC = new javax.swing.JScrollPane();
        tbl_CSVC = new javax.swing.JTable();
        jPanel_LuotThue = new javax.swing.JPanel();
        lbl_MaLuotThue = new javax.swing.JLabel();
        txt_MaLuotThue = new javax.swing.JTextField();
        lbl_NgayGio = new javax.swing.JLabel();
        txt_NgayGio = new javax.swing.JTextField();
        lbl_Coc = new javax.swing.JLabel();
        txt_Coc = new javax.swing.JTextField();
        btn_ThemLuotThue = new javax.swing.JButton();
        btn_SuaLuotThue = new javax.swing.JButton();
        btn_XoaLuotThue = new javax.swing.JButton();
        btn_TimluotThue = new javax.swing.JButton();
        jScrollPane_LuotThue = new javax.swing.JScrollPane();
        tbl_LuotThue = new javax.swing.JTable();
        lbl_MaKHLuotThue = new javax.swing.JLabel();
        txt_MaKHLuotThue = new javax.swing.JTextField();
        lbl_GhiChu = new javax.swing.JLabel();
        txt_GhiChu = new javax.swing.JTextField();
        lbl_TongTien = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jPanel_NhanVien = new javax.swing.JPanel();
        lbl_MaNV = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        lbl_HoTenNV = new javax.swing.JLabel();
        txt_HoTenNV = new javax.swing.JTextField();
        lbl_TaiKhoanNV = new javax.swing.JLabel();
        txt_TaiKhoanNV = new javax.swing.JTextField();
        btn_ThemNhanVien = new javax.swing.JButton();
        btn_SuaNhanVien = new javax.swing.JButton();
        btn_XoaNhanVien = new javax.swing.JButton();
        btn_TimNhanVien = new javax.swing.JButton();
        jScrollPane_NhanVien = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jPanel_Header = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_TieuDe = new javax.swing.JLabel();
        lbl_DeTai = new javax.swing.JLabel();
        lbl_GVHD = new javax.swing.JLabel();
        lbl_ThucHien = new javax.swing.JLabel();
        pnl_User = new javax.swing.JPanel();
        lbl_UserIcon = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        lbl_IdTag = new javax.swing.JLabel();
        lbl_headerMaNV = new javax.swing.JLabel();
        jMenu_MainForm = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_KhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaKH.setText("Mã Khách Hàng");
        jPanel_KhachHang.add(lbl_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        jPanel_KhachHang.add(txt_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 6, 224, -1));

        lbl_TenKhachHang.setText("Tên Khách Hàng");
        jPanel_KhachHang.add(lbl_TenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));
        jPanel_KhachHang.add(txt_TenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 47, 224, -1));

        lbl_SDTKhachHang.setText("Số Điện Thoại");
        jPanel_KhachHang.add(lbl_SDTKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 96, -1));
        jPanel_KhachHang.add(txt_SDTKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 88, 224, -1));

        btn_ThemKhachHang.setText("Thêm");
        btn_ThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKhachHangActionPerformed(evt);
            }
        });
        jPanel_KhachHang.add(btn_ThemKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 129, -1, -1));

        btn_SuaKhachHang.setText("Sửa");
        jPanel_KhachHang.add(btn_SuaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 129, -1, -1));

        btn_XoaKhachHang.setText("Xoá");
        jPanel_KhachHang.add(btn_XoaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 129, -1, -1));

        btn_TimKhachHang.setText("Tìm");
        jPanel_KhachHang.add(btn_TimKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, -1, -1));

        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ Tên", "Số Điện Thoại"
            }
        ));
        jScrollPaneKhachHang.setViewportView(tbl_KhachHang);

        jPanel_KhachHang.add(jScrollPaneKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 6, 880, 530));

        jTabbed_FrmMain.addTab("Khách Hàng", jPanel_KhachHang);

        jPanel_PhongHop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaPhong.setText("Mã Phòng");
        jPanel_PhongHop.add(lbl_MaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 64, -1));
        jPanel_PhongHop.add(txt_MaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 6, 256, -1));

        lbl_LoaiPhong.setText("Loại Phòng");
        jPanel_PhongHop.add(lbl_LoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));
        jPanel_PhongHop.add(txt_LoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 47, 256, -1));

        lbl_GiaTien.setText("Giá Tiền");
        jPanel_PhongHop.add(lbl_GiaTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 64, -1));
        jPanel_PhongHop.add(txt_GiaTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 88, 256, -1));

        btn_ThemPhong.setText("Thêm");
        jPanel_PhongHop.add(btn_ThemPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 129, -1, -1));

        btn_SuaPhong.setText("Sửa");
        jPanel_PhongHop.add(btn_SuaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 129, -1, -1));

        btn_XoaPhong.setText("Xoá");
        jPanel_PhongHop.add(btn_XoaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 129, -1, -1));

        btn_TimPhong.setText("Tìm");
        jPanel_PhongHop.add(btn_TimPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, -1, -1));

        tbl_PhongHop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Phong.setViewportView(tbl_PhongHop);

        jPanel_PhongHop.add(jScrollPane_Phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 6, 880, 530));

        jTabbed_FrmMain.addTab("Phòng Họp", jPanel_PhongHop);

        jPanel_CoSoVatChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaCSVC.setText("Mã CSVC");
        jPanel_CoSoVatChat.add(lbl_MaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        jPanel_CoSoVatChat.add(txt_MaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 6, 224, -1));

        lbl_LoaiCSVC.setText("Loại CSVC ");
        jPanel_CoSoVatChat.add(lbl_LoaiCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));
        jPanel_CoSoVatChat.add(txt_LoaiCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 47, 224, -1));

        lbl_GiaCSVC.setText("Giá CSVC");
        jPanel_CoSoVatChat.add(lbl_GiaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 96, -1));
        jPanel_CoSoVatChat.add(txt_GiaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 88, 224, -1));

        btn_ThemCSVC.setText("Thêm");
        jPanel_CoSoVatChat.add(btn_ThemCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 129, -1, -1));

        btn_SuaCSVC.setText("Sửa");
        jPanel_CoSoVatChat.add(btn_SuaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 129, -1, -1));

        btn_XoaCSVC.setText("Xoá");
        jPanel_CoSoVatChat.add(btn_XoaCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 129, -1, -1));

        btn_TimCSVC.setText("Tìm");
        jPanel_CoSoVatChat.add(btn_TimCSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, -1, -1));

        tbl_CSVC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_CSVC.setViewportView(tbl_CSVC);

        jPanel_CoSoVatChat.add(jScrollPane_CSVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 6, 880, 530));

        jTabbed_FrmMain.addTab("Cơ Sở Vật Chất", jPanel_CoSoVatChat);

        lbl_MaLuotThue.setText("Mã Lượt Thuê");

        lbl_NgayGio.setText("Ngày Giờ");

        lbl_Coc.setText("Cọc");

        btn_ThemLuotThue.setText("Thêm");
        btn_ThemLuotThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLuotThueActionPerformed(evt);
            }
        });

        btn_SuaLuotThue.setText("Sửa");

        btn_XoaLuotThue.setText("Xoá");

        btn_TimluotThue.setText("Tìm");

        tbl_LuotThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_LuotThue.setViewportView(tbl_LuotThue);

        lbl_MaKHLuotThue.setText("Mã Khách Hàng");

        lbl_GhiChu.setText("Ghi Chú");

        lbl_TongTien.setText("Tổng Tiền");

        javax.swing.GroupLayout jPanel_LuotThueLayout = new javax.swing.GroupLayout(jPanel_LuotThue);
        jPanel_LuotThue.setLayout(jPanel_LuotThueLayout);
        jPanel_LuotThueLayout.setHorizontalGroup(
            jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaLuotThue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NgayGio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NgayGio)
                            .addComponent(txt_MaLuotThue)))
                    .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                        .addComponent(btn_ThemLuotThue)
                        .addGap(12, 12, 12)
                        .addComponent(btn_SuaLuotThue)
                        .addGap(12, 12, 12)
                        .addComponent(btn_XoaLuotThue)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimluotThue)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LuotThueLayout.createSequentialGroup()
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                                .addComponent(lbl_Coc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                                .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_MaKHLuotThue)
                                    .addComponent(lbl_GhiChu)
                                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TongTien)
                            .addComponent(txt_GhiChu)
                            .addComponent(txt_MaKHLuotThue)
                            .addComponent(txt_Coc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_LuotThue, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_LuotThueLayout.setVerticalGroup(
            jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LuotThueLayout.createSequentialGroup()
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_MaLuotThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaLuotThue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NgayGio)
                            .addComponent(txt_NgayGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Coc)
                            .addComponent(txt_Coc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_MaKHLuotThue)
                            .addComponent(txt_MaKHLuotThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_GhiChu)
                            .addComponent(txt_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TongTien)
                            .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel_LuotThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ThemLuotThue)
                            .addComponent(btn_SuaLuotThue)
                            .addComponent(btn_XoaLuotThue)
                            .addComponent(btn_TimluotThue)))
                    .addComponent(jScrollPane_LuotThue, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbed_FrmMain.addTab("Lượt Thuê", jPanel_LuotThue);

        jPanel_NhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaNV.setText("Mã Nhân Viên");
        jPanel_NhanVien.add(lbl_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        jPanel_NhanVien.add(txt_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 6, 224, -1));

        lbl_HoTenNV.setText("Họ Tên");
        jPanel_NhanVien.add(lbl_HoTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));
        jPanel_NhanVien.add(txt_HoTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 47, 224, -1));

        lbl_TaiKhoanNV.setText("Tài Khoản");
        jPanel_NhanVien.add(lbl_TaiKhoanNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 96, -1));
        jPanel_NhanVien.add(txt_TaiKhoanNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 88, 224, -1));

        btn_ThemNhanVien.setText("Thêm");
        jPanel_NhanVien.add(btn_ThemNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 129, -1, -1));

        btn_SuaNhanVien.setText("Sửa");
        jPanel_NhanVien.add(btn_SuaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 129, -1, -1));

        btn_XoaNhanVien.setText("Xoá");
        jPanel_NhanVien.add(btn_XoaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 129, -1, -1));

        btn_TimNhanVien.setText("Tìm");
        jPanel_NhanVien.add(btn_TimNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, -1, -1));

        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_NhanVien.setViewportView(tbl_NhanVien);

        jPanel_NhanVien.add(jScrollPane_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 6, 880, 530));

        jTabbed_FrmMain.addTab("Nhân Viên", jPanel_NhanVien);

        getContentPane().add(jTabbed_FrmMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 1240, 570));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logohuce_1.png"))); // NOI18N

        lbl_TieuDe.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_TieuDe.setText("ĐỒ ÁN LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG");

        lbl_DeTai.setText("ĐỀ TÀI: QUẢN LÝ CHO THUÊ PHÒNG HỌP");

        lbl_GVHD.setText("GVHD: KS.Đỗ Hoàn");

        lbl_ThucHien.setText("THỰC HIỆN: NHÓM 1 - 66IT2");

        lbl_UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg.png"))); // NOI18N

        lbl_Username.setText("huylq");

        lbl_IdTag.setText("ID:");

        lbl_headerMaNV.setText("NV001");

        javax.swing.GroupLayout pnl_UserLayout = new javax.swing.GroupLayout(pnl_User);
        pnl_User.setLayout(pnl_UserLayout);
        pnl_UserLayout.setHorizontalGroup(
            pnl_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_UserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Username)
                    .addGroup(pnl_UserLayout.createSequentialGroup()
                        .addComponent(lbl_IdTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_headerMaNV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_UserLayout.setVerticalGroup(
            pnl_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnl_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_UserLayout.createSequentialGroup()
                        .addComponent(lbl_Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_IdTag)
                            .addComponent(lbl_headerMaNV)))
                    .addComponent(lbl_UserIcon))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_DeTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_GVHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(pnl_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                            .addComponent(lbl_TieuDe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_DeTai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_GVHD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_ThucHien))
                        .addComponent(pnl_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 120));

        jMenu1.setText("File");
        jMenu_MainForm.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu_MainForm.add(jMenu2);

        setJMenuBar(jMenu_MainForm);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemLuotThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLuotThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemLuotThueActionPerformed

    private void btn_ThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBtn_SuaCSVC() {
        return btn_SuaCSVC;
    }

    public void setBtn_SuaCSVC(JButton btn_SuaCSVC) {
        this.btn_SuaCSVC = btn_SuaCSVC;
    }

    public JButton getBtn_SuaKhachHang() {
        return btn_SuaKhachHang;
    }

    public void setBtn_SuaKhachHang(JButton btn_SuaKhachHang) {
        this.btn_SuaKhachHang = btn_SuaKhachHang;
    }

    public JButton getBtn_SuaLuotThue() {
        return btn_SuaLuotThue;
    }

    public void setBtn_SuaLuotThue(JButton btn_SuaLuotThue) {
        this.btn_SuaLuotThue = btn_SuaLuotThue;
    }

    public JButton getBtn_SuaNhanVien() {
        return btn_SuaNhanVien;
    }

    public void setBtn_SuaNhanVien(JButton btn_SuaNhanVien) {
        this.btn_SuaNhanVien = btn_SuaNhanVien;
    }

    public JButton getBtn_SuaPhong() {
        return btn_SuaPhong;
    }

    public void setBtn_SuaPhong(JButton btn_SuaPhong) {
        this.btn_SuaPhong = btn_SuaPhong;
    }

    public JButton getBtn_ThemCSVC() {
        return btn_ThemCSVC;
    }

    public void setBtn_ThemCSVC(JButton btn_ThemCSVC) {
        this.btn_ThemCSVC = btn_ThemCSVC;
    }

    public JButton getBtn_ThemKhachHang() {
        return btn_ThemKhachHang;
    }

    public void setBtn_ThemKhachHang(JButton btn_ThemKhachHang) {
        this.btn_ThemKhachHang = btn_ThemKhachHang;
    }

    public JButton getBtn_ThemLuotThue() {
        return btn_ThemLuotThue;
    }

    public void setBtn_ThemLuotThue(JButton btn_ThemLuotThue) {
        this.btn_ThemLuotThue = btn_ThemLuotThue;
    }

    public JButton getBtn_ThemNhanVien() {
        return btn_ThemNhanVien;
    }

    public void setBtn_ThemNhanVien(JButton btn_ThemNhanVien) {
        this.btn_ThemNhanVien = btn_ThemNhanVien;
    }

    public JButton getBtn_ThemPhong() {
        return btn_ThemPhong;
    }

    public void setBtn_ThemPhong(JButton btn_ThemPhong) {
        this.btn_ThemPhong = btn_ThemPhong;
    }

    public JButton getBtn_TimCSVC() {
        return btn_TimCSVC;
    }

    public void setBtn_TimCSVC(JButton btn_TimCSVC) {
        this.btn_TimCSVC = btn_TimCSVC;
    }

    public JButton getBtn_TimKhachHang() {
        return btn_TimKhachHang;
    }

    public void setBtn_TimKhachHang(JButton btn_TimKhachHang) {
        this.btn_TimKhachHang = btn_TimKhachHang;
    }

    public JButton getBtn_TimNhanVien() {
        return btn_TimNhanVien;
    }

    public void setBtn_TimNhanVien(JButton btn_TimNhanVien) {
        this.btn_TimNhanVien = btn_TimNhanVien;
    }

    public JButton getBtn_TimPhong() {
        return btn_TimPhong;
    }

    public void setBtn_TimPhong(JButton btn_TimPhong) {
        this.btn_TimPhong = btn_TimPhong;
    }

    public JButton getBtn_TimluotThue() {
        return btn_TimluotThue;
    }

    public void setBtn_TimluotThue(JButton btn_TimluotThue) {
        this.btn_TimluotThue = btn_TimluotThue;
    }

    public JButton getBtn_XoaCSVC() {
        return btn_XoaCSVC;
    }

    public void setBtn_XoaCSVC(JButton btn_XoaCSVC) {
        this.btn_XoaCSVC = btn_XoaCSVC;
    }

    public JButton getBtn_XoaKhachHang() {
        return btn_XoaKhachHang;
    }

    public void setBtn_XoaKhachHang(JButton btn_XoaKhachHang) {
        this.btn_XoaKhachHang = btn_XoaKhachHang;
    }

    public JButton getBtn_XoaLuotThue() {
        return btn_XoaLuotThue;
    }

    public void setBtn_XoaLuotThue(JButton btn_XoaLuotThue) {
        this.btn_XoaLuotThue = btn_XoaLuotThue;
    }

    public JButton getBtn_XoaNhanVien() {
        return btn_XoaNhanVien;
    }

    public void setBtn_XoaNhanVien(JButton btn_XoaNhanVien) {
        this.btn_XoaNhanVien = btn_XoaNhanVien;
    }

    public JButton getBtn_XoaPhong() {
        return btn_XoaPhong;
    }

    public void setBtn_XoaPhong(JButton btn_XoaPhong) {
        this.btn_XoaPhong = btn_XoaPhong;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenu_MainForm() {
        return jMenu_MainForm;
    }

    public void setjMenu_MainForm(JMenuBar jMenu_MainForm) {
        this.jMenu_MainForm = jMenu_MainForm;
    }

    public JPanel getjPanel_CoSoVatChat() {
        return jPanel_CoSoVatChat;
    }

    public void setjPanel_CoSoVatChat(JPanel jPanel_CoSoVatChat) {
        this.jPanel_CoSoVatChat = jPanel_CoSoVatChat;
    }

    public JPanel getjPanel_Header() {
        return jPanel_Header;
    }

    public void setjPanel_Header(JPanel jPanel_Header) {
        this.jPanel_Header = jPanel_Header;
    }

    public JPanel getjPanel_KhachHang() {
        return jPanel_KhachHang;
    }

    public void setjPanel_KhachHang(JPanel jPanel_KhachHang) {
        this.jPanel_KhachHang = jPanel_KhachHang;
    }

    public JPanel getjPanel_LuotThue() {
        return jPanel_LuotThue;
    }

    public void setjPanel_LuotThue(JPanel jPanel_LuotThue) {
        this.jPanel_LuotThue = jPanel_LuotThue;
    }

    public JPanel getjPanel_NhanVien() {
        return jPanel_NhanVien;
    }

    public void setjPanel_NhanVien(JPanel jPanel_NhanVien) {
        this.jPanel_NhanVien = jPanel_NhanVien;
    }

    public JPanel getjPanel_PhongHop() {
        return jPanel_PhongHop;
    }

    public void setjPanel_PhongHop(JPanel jPanel_PhongHop) {
        this.jPanel_PhongHop = jPanel_PhongHop;
    }

    public JScrollPane getjScrollPaneKhachHang() {
        return jScrollPaneKhachHang;
    }

    public void setjScrollPaneKhachHang(JScrollPane jScrollPaneKhachHang) {
        this.jScrollPaneKhachHang = jScrollPaneKhachHang;
    }

    public JScrollPane getjScrollPane_CSVC() {
        return jScrollPane_CSVC;
    }

    public void setjScrollPane_CSVC(JScrollPane jScrollPane_CSVC) {
        this.jScrollPane_CSVC = jScrollPane_CSVC;
    }

    public JScrollPane getjScrollPane_LuotThue() {
        return jScrollPane_LuotThue;
    }

    public void setjScrollPane_LuotThue(JScrollPane jScrollPane_LuotThue) {
        this.jScrollPane_LuotThue = jScrollPane_LuotThue;
    }

    public JScrollPane getjScrollPane_NhanVien() {
        return jScrollPane_NhanVien;
    }

    public void setjScrollPane_NhanVien(JScrollPane jScrollPane_NhanVien) {
        this.jScrollPane_NhanVien = jScrollPane_NhanVien;
    }

    public JScrollPane getjScrollPane_Phong() {
        return jScrollPane_Phong;
    }

    public void setjScrollPane_Phong(JScrollPane jScrollPane_Phong) {
        this.jScrollPane_Phong = jScrollPane_Phong;
    }

    public JTabbedPane getjTabbed_FrmMain() {
        return jTabbed_FrmMain;
    }

    public void setjTabbed_FrmMain(JTabbedPane jTabbed_FrmMain) {
        this.jTabbed_FrmMain = jTabbed_FrmMain;
    }

    public JLabel getLbl_Coc() {
        return lbl_Coc;
    }

    public void setLbl_Coc(JLabel lbl_Coc) {
        this.lbl_Coc = lbl_Coc;
    }

    public JLabel getLbl_DeTai() {
        return lbl_DeTai;
    }

    public void setLbl_DeTai(JLabel lbl_DeTai) {
        this.lbl_DeTai = lbl_DeTai;
    }

    public JLabel getLbl_GVHD() {
        return lbl_GVHD;
    }

    public void setLbl_GVHD(JLabel lbl_GVHD) {
        this.lbl_GVHD = lbl_GVHD;
    }

    public JLabel getLbl_GhiChu() {
        return lbl_GhiChu;
    }

    public void setLbl_GhiChu(JLabel lbl_GhiChu) {
        this.lbl_GhiChu = lbl_GhiChu;
    }

    public JLabel getLbl_GiaCSVC() {
        return lbl_GiaCSVC;
    }

    public void setLbl_GiaCSVC(JLabel lbl_GiaCSVC) {
        this.lbl_GiaCSVC = lbl_GiaCSVC;
    }

    public JLabel getLbl_GiaTien() {
        return lbl_GiaTien;
    }

    public void setLbl_GiaTien(JLabel lbl_GiaTien) {
        this.lbl_GiaTien = lbl_GiaTien;
    }

    public JLabel getLbl_HoTenNV() {
        return lbl_HoTenNV;
    }

    public void setLbl_HoTenNV(JLabel lbl_HoTenNV) {
        this.lbl_HoTenNV = lbl_HoTenNV;
    }

    public JLabel getLbl_IdTag() {
        return lbl_IdTag;
    }

    public void setLbl_IdTag(JLabel lbl_IdTag) {
        this.lbl_IdTag = lbl_IdTag;
    }

    public JLabel getLbl_LoaiCSVC() {
        return lbl_LoaiCSVC;
    }

    public void setLbl_LoaiCSVC(JLabel lbl_LoaiCSVC) {
        this.lbl_LoaiCSVC = lbl_LoaiCSVC;
    }

    public JLabel getLbl_LoaiPhong() {
        return lbl_LoaiPhong;
    }

    public void setLbl_LoaiPhong(JLabel lbl_LoaiPhong) {
        this.lbl_LoaiPhong = lbl_LoaiPhong;
    }

    public JLabel getLbl_Logo() {
        return lbl_Logo;
    }

    public void setLbl_Logo(JLabel lbl_Logo) {
        this.lbl_Logo = lbl_Logo;
    }

    public JLabel getLbl_MaCSVC() {
        return lbl_MaCSVC;
    }

    public void setLbl_MaCSVC(JLabel lbl_MaCSVC) {
        this.lbl_MaCSVC = lbl_MaCSVC;
    }

    public JLabel getLbl_MaKH() {
        return lbl_MaKH;
    }

    public void setLbl_MaKH(JLabel lbl_MaKH) {
        this.lbl_MaKH = lbl_MaKH;
    }

    public JLabel getLbl_MaKHLuotThue() {
        return lbl_MaKHLuotThue;
    }

    public void setLbl_MaKHLuotThue(JLabel lbl_MaKHLuotThue) {
        this.lbl_MaKHLuotThue = lbl_MaKHLuotThue;
    }

    public JLabel getLbl_MaLuotThue() {
        return lbl_MaLuotThue;
    }

    public void setLbl_MaLuotThue(JLabel lbl_MaLuotThue) {
        this.lbl_MaLuotThue = lbl_MaLuotThue;
    }

    public JLabel getLbl_MaNV() {
        return lbl_MaNV;
    }

    public void setLbl_MaNV(JLabel lbl_MaNV) {
        this.lbl_MaNV = lbl_MaNV;
    }

    public JLabel getLbl_MaPhong() {
        return lbl_MaPhong;
    }

    public void setLbl_MaPhong(JLabel lbl_MaPhong) {
        this.lbl_MaPhong = lbl_MaPhong;
    }

    public JLabel getLbl_NgayGio() {
        return lbl_NgayGio;
    }

    public void setLbl_NgayGio(JLabel lbl_NgayGio) {
        this.lbl_NgayGio = lbl_NgayGio;
    }

    public JLabel getLbl_SDTKhachHang() {
        return lbl_SDTKhachHang;
    }

    public void setLbl_SDTKhachHang(JLabel lbl_SDTKhachHang) {
        this.lbl_SDTKhachHang = lbl_SDTKhachHang;
    }

    public JLabel getLbl_TaiKhoanNV() {
        return lbl_TaiKhoanNV;
    }

    public void setLbl_TaiKhoanNV(JLabel lbl_TaiKhoanNV) {
        this.lbl_TaiKhoanNV = lbl_TaiKhoanNV;
    }

    public JLabel getLbl_TenKhachHang() {
        return lbl_TenKhachHang;
    }

    public void setLbl_TenKhachHang(JLabel lbl_TenKhachHang) {
        this.lbl_TenKhachHang = lbl_TenKhachHang;
    }

    public JLabel getLbl_ThucHien() {
        return lbl_ThucHien;
    }

    public void setLbl_ThucHien(JLabel lbl_ThucHien) {
        this.lbl_ThucHien = lbl_ThucHien;
    }

    public JLabel getLbl_TieuDe() {
        return lbl_TieuDe;
    }

    public void setLbl_TieuDe(JLabel lbl_TieuDe) {
        this.lbl_TieuDe = lbl_TieuDe;
    }

    public JLabel getLbl_TongTien() {
        return lbl_TongTien;
    }

    public void setLbl_TongTien(JLabel lbl_TongTien) {
        this.lbl_TongTien = lbl_TongTien;
    }

    public JLabel getLbl_UserIcon() {
        return lbl_UserIcon;
    }

    public void setLbl_UserIcon(JLabel lbl_UserIcon) {
        this.lbl_UserIcon = lbl_UserIcon;
    }

    public JLabel getLbl_Username() {
        return lbl_Username;
    }

    public void setLbl_Username(JLabel lbl_Username) {
        this.lbl_Username = lbl_Username;
    }

    public JLabel getLbl_headerMaNV() {
        return lbl_headerMaNV;
    }

    public void setLbl_headerMaNV(JLabel lbl_headerMaNV) {
        this.lbl_headerMaNV = lbl_headerMaNV;
    }

    public JPanel getPnl_User() {
        return pnl_User;
    }

    public void setPnl_User(JPanel pnl_User) {
        this.pnl_User = pnl_User;
    }

    public JTable getTbl_CSVC() {
        return tbl_CSVC;
    }

    public void setTbl_CSVC(JTable tbl_CSVC) {
        this.tbl_CSVC = tbl_CSVC;
    }

    public JTable getTbl_KhachHang() {
        return tbl_KhachHang;
    }

    public void setTbl_KhachHang(JTable tbl_KhachHang) {
        this.tbl_KhachHang = tbl_KhachHang;
    }

    public JTable getTbl_LuotThue() {
        return tbl_LuotThue;
    }

    public void setTbl_LuotThue(JTable tbl_LuotThue) {
        this.tbl_LuotThue = tbl_LuotThue;
    }

    public JTable getTbl_NhanVien() {
        return tbl_NhanVien;
    }

    public void setTbl_NhanVien(JTable tbl_NhanVien) {
        this.tbl_NhanVien = tbl_NhanVien;
    }

    public JTable getTbl_PhongHop() {
        return tbl_PhongHop;
    }

    public void setTbl_PhongHop(JTable tbl_PhongHop) {
        this.tbl_PhongHop = tbl_PhongHop;
    }

    public JTextField getTxt_Coc() {
        return txt_Coc;
    }

    public void setTxt_Coc(JTextField txt_Coc) {
        this.txt_Coc = txt_Coc;
    }

    public JTextField getTxt_GhiChu() {
        return txt_GhiChu;
    }

    public void setTxt_GhiChu(JTextField txt_GhiChu) {
        this.txt_GhiChu = txt_GhiChu;
    }

    public JTextField getTxt_GiaCSVC() {
        return txt_GiaCSVC;
    }

    public void setTxt_GiaCSVC(JTextField txt_GiaCSVC) {
        this.txt_GiaCSVC = txt_GiaCSVC;
    }

    public JTextField getTxt_GiaTien() {
        return txt_GiaTien;
    }

    public void setTxt_GiaTien(JTextField txt_GiaTien) {
        this.txt_GiaTien = txt_GiaTien;
    }

    public JTextField getTxt_HoTenNV() {
        return txt_HoTenNV;
    }

    public void setTxt_HoTenNV(JTextField txt_HoTenNV) {
        this.txt_HoTenNV = txt_HoTenNV;
    }

    public JTextField getTxt_LoaiCSVC() {
        return txt_LoaiCSVC;
    }

    public void setTxt_LoaiCSVC(JTextField txt_LoaiCSVC) {
        this.txt_LoaiCSVC = txt_LoaiCSVC;
    }

    public JTextField getTxt_LoaiPhong() {
        return txt_LoaiPhong;
    }

    public void setTxt_LoaiPhong(JTextField txt_LoaiPhong) {
        this.txt_LoaiPhong = txt_LoaiPhong;
    }

    public JTextField getTxt_MaCSVC() {
        return txt_MaCSVC;
    }

    public void setTxt_MaCSVC(JTextField txt_MaCSVC) {
        this.txt_MaCSVC = txt_MaCSVC;
    }

    public JTextField getTxt_MaKH() {
        return txt_MaKH;
    }

    public void setTxt_MaKH(JTextField txt_MaKH) {
        this.txt_MaKH = txt_MaKH;
    }

    public JTextField getTxt_MaKHLuotThue() {
        return txt_MaKHLuotThue;
    }

    public void setTxt_MaKHLuotThue(JTextField txt_MaKHLuotThue) {
        this.txt_MaKHLuotThue = txt_MaKHLuotThue;
    }

    public JTextField getTxt_MaLuotThue() {
        return txt_MaLuotThue;
    }

    public void setTxt_MaLuotThue(JTextField txt_MaLuotThue) {
        this.txt_MaLuotThue = txt_MaLuotThue;
    }

    public JTextField getTxt_MaNV() {
        return txt_MaNV;
    }

    public void setTxt_MaNV(JTextField txt_MaNV) {
        this.txt_MaNV = txt_MaNV;
    }

    public JTextField getTxt_MaPhong() {
        return txt_MaPhong;
    }

    public void setTxt_MaPhong(JTextField txt_MaPhong) {
        this.txt_MaPhong = txt_MaPhong;
    }

    public JTextField getTxt_NgayGio() {
        return txt_NgayGio;
    }

    public void setTxt_NgayGio(JTextField txt_NgayGio) {
        this.txt_NgayGio = txt_NgayGio;
    }

    public JTextField getTxt_SDTKhachHang() {
        return txt_SDTKhachHang;
    }

    public void setTxt_SDTKhachHang(JTextField txt_SDTKhachHang) {
        this.txt_SDTKhachHang = txt_SDTKhachHang;
    }

    public JTextField getTxt_TaiKhoanNV() {
        return txt_TaiKhoanNV;
    }

    public void setTxt_TaiKhoanNV(JTextField txt_TaiKhoanNV) {
        this.txt_TaiKhoanNV = txt_TaiKhoanNV;
    }

    public JTextField getTxt_TenKhachHang() {
        return txt_TenKhachHang;
    }

    public void setTxt_TenKhachHang(JTextField txt_TenKhachHang) {
        this.txt_TenKhachHang = txt_TenKhachHang;
    }

    public JTextField getTxt_TongTien() {
        return txt_TongTien;
    }

    public void setTxt_TongTien(JTextField txt_TongTien) {
        this.txt_TongTien = txt_TongTien;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SuaCSVC;
    private javax.swing.JButton btn_SuaKhachHang;
    private javax.swing.JButton btn_SuaLuotThue;
    private javax.swing.JButton btn_SuaNhanVien;
    private javax.swing.JButton btn_SuaPhong;
    private javax.swing.JButton btn_ThemCSVC;
    private javax.swing.JButton btn_ThemKhachHang;
    private javax.swing.JButton btn_ThemLuotThue;
    private javax.swing.JButton btn_ThemNhanVien;
    private javax.swing.JButton btn_ThemPhong;
    private javax.swing.JButton btn_TimCSVC;
    private javax.swing.JButton btn_TimKhachHang;
    private javax.swing.JButton btn_TimNhanVien;
    private javax.swing.JButton btn_TimPhong;
    private javax.swing.JButton btn_TimluotThue;
    private javax.swing.JButton btn_XoaCSVC;
    private javax.swing.JButton btn_XoaKhachHang;
    private javax.swing.JButton btn_XoaLuotThue;
    private javax.swing.JButton btn_XoaNhanVien;
    private javax.swing.JButton btn_XoaPhong;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenu_MainForm;
    private javax.swing.JPanel jPanel_CoSoVatChat;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JPanel jPanel_KhachHang;
    private javax.swing.JPanel jPanel_LuotThue;
    private javax.swing.JPanel jPanel_NhanVien;
    private javax.swing.JPanel jPanel_PhongHop;
    private javax.swing.JScrollPane jScrollPaneKhachHang;
    private javax.swing.JScrollPane jScrollPane_CSVC;
    private javax.swing.JScrollPane jScrollPane_LuotThue;
    private javax.swing.JScrollPane jScrollPane_NhanVien;
    private javax.swing.JScrollPane jScrollPane_Phong;
    private javax.swing.JTabbedPane jTabbed_FrmMain;
    private javax.swing.JLabel lbl_Coc;
    private javax.swing.JLabel lbl_DeTai;
    private javax.swing.JLabel lbl_GVHD;
    private javax.swing.JLabel lbl_GhiChu;
    private javax.swing.JLabel lbl_GiaCSVC;
    private javax.swing.JLabel lbl_GiaTien;
    private javax.swing.JLabel lbl_HoTenNV;
    private javax.swing.JLabel lbl_IdTag;
    private javax.swing.JLabel lbl_LoaiCSVC;
    private javax.swing.JLabel lbl_LoaiPhong;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_MaCSVC;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaKHLuotThue;
    private javax.swing.JLabel lbl_MaLuotThue;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_MaPhong;
    private javax.swing.JLabel lbl_NgayGio;
    private javax.swing.JLabel lbl_SDTKhachHang;
    private javax.swing.JLabel lbl_TaiKhoanNV;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_ThucHien;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JLabel lbl_UserIcon;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_headerMaNV;
    private javax.swing.JPanel pnl_User;
    private javax.swing.JTable tbl_CSVC;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTable tbl_LuotThue;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JTable tbl_PhongHop;
    private javax.swing.JTextField txt_Coc;
    private javax.swing.JTextField txt_GhiChu;
    private javax.swing.JTextField txt_GiaCSVC;
    private javax.swing.JTextField txt_GiaTien;
    private javax.swing.JTextField txt_HoTenNV;
    private javax.swing.JTextField txt_LoaiCSVC;
    private javax.swing.JTextField txt_LoaiPhong;
    private javax.swing.JTextField txt_MaCSVC;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaKHLuotThue;
    private javax.swing.JTextField txt_MaLuotThue;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaPhong;
    private javax.swing.JTextField txt_NgayGio;
    private javax.swing.JTextField txt_SDTKhachHang;
    private javax.swing.JTextField txt_TaiKhoanNV;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
